# Generated by Django 4.1.6 on 2023-02-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('places', models.IntegerField(default=4)),
                ('puissance', models.IntegerField(default=10)),
                ('capacité_du_Reservoir_en_litre', models.IntegerField(default=50)),
                ('caracteristiques_moteur', models.TextField(max_length=500)),
            ],
        ),
    ]
