# Generated by Django 4.1.6 on 2023-02-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_nom_voiture_marque'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='voiture',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cars'),
        ),
    ]
