# Generated by Django 4.1.6 on 2023-02-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_voiture_slug_voiture_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='slug',
        ),
        migrations.AlterField(
            model_name='voiture',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
