# Generated by Django 4.1.6 on 2023-02-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_voiture_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=128)),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
