# Generated by Django 4.1.6 on 2023-02-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_voiture_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='prix_en_dollars',
            field=models.FloatField(default=5000),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
