# Generated by Django 4.1.6 on 2023-02-25 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_voiture_prix_en_dollars_alter_voiture_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiture',
            old_name='caracteristiques_moteur',
            new_name='caracteristiques_du_moteur_et_details_du_vehicule',
        ),
    ]
